# Section 1: Intro

## Creating Arrays

In [3]:
import numpy as np

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5,7,12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [8]:
a[2]

np.int64(3)

In [9]:
a[2] = 10

In [10]:
a

array([ 1,  2, 10,  4,  5,  7, 12])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multidimentional Arrays

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
    [1,2,3,],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[:,2]

array([3, 6, 9])

In [16]:
n[2]=[1,1,1]

ERROR! Session/line number was not unique in database. History logging moved to new session 2


In [17]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [18]:
n[0,2] = 20
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 1,  1,  1]])

## Randomly Generated Arrays

In [19]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [21]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [22]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise Operations

In [23]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
a + 1

array([1, 2, 3, 4, 5])

In [25]:
a * 2

array([0, 2, 4, 6, 8])

In [26]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [27]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [28]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison Operations

In [29]:
a

array([0, 1, 2, 3, 4])

In [30]:
a >= 2

array([False, False,  True,  True,  True])

In [31]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a > b

array([False, False,  True,  True,  True])

In [33]:
a[a > b]

array([2, 3, 4])

## Summarizing Operations

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a.min()

np.int64(0)

In [36]:
a.max()

np.int64(4)

In [37]:
 a.mean()

np.float64(2.0)

In [38]:
a.std()

np.float64(1.4142135623730951)

In [39]:
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [40]:
n.sum()

np.int64(41)

In [41]:
n.min()

np.int64(1)

## Multiplication

In [63]:
u = np.array([1,2,3])
v = np.array([5,6,7])

In [64]:
def vector_vector_multiplication(u, v):
    assert u.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [65]:
vector_vector_multiplication(u, v)

np.float64(38.0)

In [66]:
u.dot(v)

np.int64(38)

In [67]:
U = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])

In [72]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)

    return result

In [73]:
matrix_vector_multiplication(U, v)

array([25., 10., 19., 16.])

In [74]:
U.dot(v)

array([25., 10., 19., 16.])

## Matrix-matrix multiplication

In [79]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1] 

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [95]:
V= np.array([
    [1,2,3],
    [3,6,4],
    [5,6,8]
])

In [96]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 23. ],
       [ 6.5,  9. , 10. ],
       [11. , 18. , 16. ],
       [ 5. , 10. , 10. ]])

In [97]:
U.dot(V)

array([[14. , 20. , 23. ],
       [ 6.5,  9. , 10. ],
       [11. , 18. , 16. ],
       [ 5. , 10. , 10. ]])

## Identity Matrix

In [98]:
I = np.eye(3)

In [99]:
V

array([[1, 2, 3],
       [3, 6, 4],
       [5, 6, 8]])

In [100]:
V.dot(I)

array([[1., 2., 3.],
       [3., 6., 4.],
       [5., 6., 8.]])

## Inverse

In [101]:
Vs = V[[0,1,2]]
Vs

array([[1, 2, 3],
       [3, 6, 4],
       [5, 6, 8]])

In [102]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[-1.2000000e+00, -1.0000000e-01,  5.0000000e-01],
       [ 2.0000000e-01,  3.5000000e-01, -2.5000000e-01],
       [ 6.0000000e-01, -2.0000000e-01,  4.4408921e-18]])

In [104]:
Vs_inv.dot(Vs)

array([[ 1.00000000e+00,  2.22044605e-16,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 4.99600361e-17,  8.21565038e-17,  1.00000000e+00]])